"""add sources and reasoning to messages

Revision ID: 329e20890a7e
Revises: 78a7ca80bd3f
Create Date: 2026-05-17 18:56:20.061297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '329e20890a7e'
down_revision: Union[str, Sequence[str], None] = '78a7ca80bd3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sources', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('reasoning', sa.Text(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    op.drop_column('messages', 'reasoning')
    op.drop_column('messages', 'sources')
    # ### end Alembic commands ###
